# Generated by Django 3.1.1 on 2020-09-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='item_image',
            field=models.CharField(default='https://cdn2.vectorstock.com/i/1000x1000/42/61/alpine-skiing-line-icon-sport-and-winter-skier-vector-25904261.jpg', max_length=500),
        ),
    ]
